---
name: "release"

on:
  push:
    branches:
      - "master"
    tags:
      - "release"

jobs:
  pre-release:
    name: "pre-release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build artifacts"
        run: make docker

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/*
